INSERT INTO specialite (numero, lib, codeType, ingredients, description) VALUES
("01", "Bœuf de race limousine", 2, "Viande de bœuf limousin.", "Viande très goûteuse."),
("01", "Moutarde à la violette", 8, "Graines de moutarde, moût de raisin.", "Mélange de graines de moutarde et de moût de raisin."),
("01", "Châtaigne", 4, "Châtaignes.", "Fruit qui a apporté pendant des siècles la nourriture et la gagne-pain de ses habitants."),
("01", "Clafoutis", 3, "Cerises, œufs, farine, lait.", "Flan composé de cerises avec leur noyau."),
("01", "Mirabelle de Lorraine", 9, "Mirabelles.", "Savourée en tarte, confiture, eau-de-vie ou encore nature."),
("01", "Munster AOC des Vosges", 7, "Lait, ferments, présure.", "Au goût et à l'odorat prononcé !"),
("01", "Quiche lorraine", 2, "Pâte brisée, lardons, crème, œufs.", "Garnie de lardons."),
("01", "Pâté lorrain", 2, "Viande, pâte feuilletée, vin.", "Préparé la veille par marinade de la viande dans du vin rouge ou blanc."),
("01", "Bergamotes de Nancy", 4, "Sucre, arôme de bergamote.", "Bonbon carré, translucide et plat parfumé à l’huile essentielle de bergamote."),
("01", "Volailles du Gers", 2, "Volaille.", "Poulets, chapons, poulardes, pintades et dindes, qui sont estampillées Label Rouge."),
("01", "Foie gras de canard", 2, "Foie gras de canard.", ""),
("01", "Truffe noire", 2, "Truffes, œufs.", "Dégustée en omelette."),
("01", "Ail Rose de Lautrec", 8, "Ail rose.", ""),
("01", "Fromages", 7, "Lait, ferments, présure.", "Roquefort, Bleu des Causses, Tomme des Pyrénées, Rocamadour."),
("01", "Carbonade Flamande", 2, "Bœuf, bière, oignons.", "Sorte de bœuf bourguignon dans lequel on remplace le vin par la bière."),
("01", "Waterzooï de poulet", 2, "Poulet, bouillon, crème, légumes.", "Poulet ou poisson cuit dans un bouillon de crème, accompagné de petits légumes."),
("01", "Moules frites", 2, "Moules, pommes de terre, frites.", "Notamment consommé à la braderie de Lille."),
("01", "Bières", 8, "Orge, houblon, eau, levure.", "Angelus, Grain d'Orge, Goudale, Jenlain, La Choulette, Moulin d'Ascq, ..."),
("01", "Andouille de Vire", 2, "Intestin de porc.", "Constituée de gros intestin de porc."),
("01", "Tripes à la mode de Caen", 2, "Tripes, vin, épices.", "Fait à base des quatre parties de l'estomac de bœuf."),
("01", "Camembert", 7, "Lait, ferments, présure.", "Fromage de lait cru de vache, d'appellation AOP."),
("01", "Omelette de la mère Poulard", 1, "Œufs, beurre.", ""),
("01", "Lapin au cidre", 2, "Lapin, cidre, oignons.", ""),
("01", "Pommes de Normandie", 3, "Pommes.", "À déguster en tarte, cidre, calvados. Goûtez le pommeau."),
("01", "Rillettes du Mans", 1, "Viande de porc, gras, épices.", "À tartiner sur du pain."),
("01", "Biscuits LU de Nantes", 4, "Farine, sucre, beurre.", ""),
("01", "Fouace nantaise", 4, "Farine, sucre, beurre, œufs.", "Pâtisserie sucrée en forme d'étoile à six branches."),
("01", "Sel de Guérande", 8, "Sel.", "Façonné par cinq éléments : la mer, le vent, le soleil, l'argile et les hommes."),
("01", "Maroilles", 7, "Lait, ferments, présure.", "Fromage très odorant, produit dans le Nord et l'Aine."),
("01", "Compiégnois", 4, "Farine, sucre, ananas.", "Aussi appelé 'dessert de Napoléon'. Gâteau fait de pâte levée, coupé en tranche et intercalé des rondelles d'ananas."),
("01", "Rabote", 4, "Pomme, sucre, pâte feuilletée.", "Pomme pelée remplie de sucre cuite dans une pâte feuilletée."),
("01", "Crème chantilly", 9, "Crème, sucre.", "Crème fouettée sucrée.");